"""Record the single authentic auth result and stop state, never contact the broker."""
import hashlib,json
from pathlib import Path
from .read_only_auth_preflight_v2 import validate_safe,GATES
S=Path('adaptive_competition/state')
def save(path,j):Path(path).write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
def main():
 r=json.loads((S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V2.json').read_text());validate_safe(r)
 assert r['execution_head']=='205ea6667bc604de4181631cb7f264e80cf6888c'
 next_action='PENDING_INDEPENDENT_AUDIT_OF_MACHINE_SIDE_READ_ONLY_AUTH_V2_BEFORE_ANY_MARKET_DATA_ACQUISITION' if r['auth_proven'] else 'PENDING_INDEPENDENT_AUDIT_OF_MACHINE_SIDE_READ_ONLY_AUTH_V2_FAILURE'
 p=S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V2_VALIDATION.json';v=json.loads(p.read_text());v.update({'status':'PASS_POSTAUTH_SAFE_ARTIFACT_AND_HISTORICAL_INTEGRITY_VALIDATION','auth_attempt_executed':True,'auth_status':r['status'],'safe_reason':r['safe_reason'],'authentic_result_sha256':hashlib.sha256((S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V2.json').read_bytes()).hexdigest(),'downloaded_actions_artifact_sha256':'c2f7f4f2a4bc5e41427d02385338749043775cb3fadc8531bda83ace3e721cb8','downloaded_artifact_json_byte_identical':True,'safe_schema_verified':True,'preauth_source_head':r['exact_source_head'],'execution_head':r['execution_head'],'result_persisted_before_interpretation_head':'7b1fac9319f30ba002d9d4ee7953752dde53a834','preauth_bounded_ci_run_id':37464475265,'auth_run_id':37464618123,'auth_job_id':112272424620,'auth_artifact_id':11413383320,'auth_workflow_conclusion':'success;BROKER_PREFLIGHT_FAILED_CLOSED_IS_RESULT_NOT_WORKFLOW_CRASH','authentication_attempt_count':1,'authenticated_retry_count':0,'three_runtime_secrets_present':True,'refresh_token_presence_confirmed_without_auth_process_inheritance':True,'no_history_order_refresh_subscription_contact':True,'transport_closed':True,'post_run_gate_results':{k:r[k] for k in GATES},'failed_gate':'broker_region_pass' if r['safe_reason']=='BROKER_REGION_NOT_VERIFIED' else r['safe_reason'],'gates_not_evaluated_after_failure':['hedged_account_pass','max_margin_mode_pass','non_swap_free_pass','eur_deposit_asset_pass'] if r['safe_reason']=='BROKER_REGION_NOT_VERIFIED' else [],'failure_interpretation':'Strict brokerName requires both Pepperstone and Europe. Gate was not verified; safe artifact intentionally contains no raw broker payload, account ID, login or credentials. Do not infer that other account semantics failed; they were not evaluated after this gate. No retry, alternate account, gate relaxation or further contact authorized.','no_new_economic_identity':True,'budget_consumed':0,'next_action':next_action});save(p,v)
 p=S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V2_AUTHORITY.json';j=json.loads(p.read_text());j.setdefault('frozen_preauth_authority_sha256',hashlib.sha256(p.read_bytes()).hexdigest());j.update({'preauth_status':j.get('preauth_status',j['status']),'status':r['status'],'attempt_completed':True,'exact_source_head':r['exact_source_head'],'execution_head':r['execution_head'],'result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V2.json','result_sha256':v['authentic_result_sha256'],'validation_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V2_VALIDATION.json','next_action':next_action,'broker_contact_authorized_after_result':False});save(p,j)
 p=S/'ADAPTIVE_COMPETITION_CURRENT_STATE.json';j=json.loads(p.read_text());j.update({'machine_side_auth_status':r['status'],'machine_side_auth_v2_result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V2.json','machine_side_auth_v2_safe_reason':r['safe_reason'],'next_action':next_action});save(p,j)
 p=S/'ADAPTIVE_COMPETITION_AUTHORITY_V1.json';j=json.loads(p.read_text());j['current_operation']=next_action;save(p,j)
 p=S/'MACHINE_SIDE_READ_ONLY_RESEARCH_AUTH_FOLLOWUP_STATE.json';j=json.loads(p.read_text());j.update({'status':r['status'],'auth_proven':r['auth_proven'],'secret_provisioning_verified':True,'secret_names_presence_checked':True,'secret_values_provisioned':True,'secret_values_inspected':False,'runtime_required_secret_names':['CTRADER_CLIENT_ID','CTRADER_CLIENT_SECRET','CTRADER_ACCESS_TOKEN'],'required_prospective_secret_names':['CTRADER_CLIENT_ID','CTRADER_CLIENT_SECRET','CTRADER_ACCESS_TOKEN','CTRADER_REFRESH_TOKEN'],'expected_account_id_secret_required':False,'account_identity':'AUTODISCOVER_UNIQUE_EXISTING_HISTORICAL_FINGERPRINT_MATCH','user_security_action_required_now':False,'current_user_security_steps':[],'historical_user_action_blocker_ref':j.get('user_action_blocker_ref'),'user_action_blocker_ref':None,'deterministic_preflight_code_ref':'adaptive_competition/read_only_auth_preflight_v2.py','workflow_ref':'.github/workflows/adaptive-read-only-auth-preflight-v2.yml','current_authority_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V2_AUTHORITY.json','result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V2.json','result_sha256':v['authentic_result_sha256'],'next_gate':next_action,'broker_contact_this_task':r['broker_contact_attempted'],'historical_acquisition_this_task':False,'refresh_token_present':True,'refresh_token_used':False,'refresh_attempted':False,'tiny_preflight_access_token_strategy':'CTRADER_ACCESS_TOKEN_ONLY_NO_REFRESH_NO_EXPECTED_ACCOUNT_ID','preflight_failure_safe_reason':r['safe_reason'],'deterministic_preflight_sequence':['ApplicationAuth','GetAccountListByAccessToken','Require explicit SCOPE_VIEW','Unique historical account fingerprint autodiscovery','Require LIVE','AccountAuth','TraderReq strict Pepperstone Europe/HEDGED/MAX/non-swap-free gates','AssetListReq EUR gate','Close transport'],'future_acquisition_authorized':False});save(p,j)
 p=Path('CURRENT_STATE.json');j=json.loads(p.read_text());j.update({'next_action':next_action,'phase':next_action,'machine_side_auth_v2_status':r['status']});save(p,j)
 p=Path('research_core_v4/state/V4_STATE.json');j=json.loads(p.read_text());j.update({'current_next_action_type':next_action,'next_action':next_action,'status':'MACHINE_SIDE_READ_ONLY_AUTH_V2_COMPLETED_FAIL_CLOSED_PENDING_INDEPENDENT_AUDIT' if not r['auth_proven'] else 'MACHINE_SIDE_READ_ONLY_AUTH_V2_PROVEN_PENDING_INDEPENDENT_AUDIT','machine_side_auth_v2_status':r['status']});save(p,j)
if __name__=='__main__':main()
