"""Persist interpretation/governance only; never changes historical policy/result/budget."""
import json,hashlib
from pathlib import Path
from .data import STATE,save,ROOT
NEXT='PENDING_USER_SECURITY_ACTION_FOR_MACHINE_SIDE_READ_ONLY_AUTH_AFTER_COMPLETED_ADAPTIVE_V1_CAUSAL_DIAGNOSTIC'
BASE='1247015532d748b5d02aa97b850c999e10ee4aad'
CLASS='MIXED_FORECAST_AND_FRICTION_LIMITATION'
def main():
 gate=json.loads((STATE/'ADAPTIVE_V1_POST_OUTCOME_CAUSAL_GATE_DECOMPOSITION_V1.json').read_text());counts=gate['stage_counts_aggregate'];funnel=gate['sequential_positive_funnel_aggregate']
 assert counts['forecast_nonzero_count']==28537188 and counts['uncertainty_adjusted_positive_count']==7124 and funnel['positive_after_uncertainty_cost_and_conversion_supported']==125 and counts['positive_after_spread_only_count']==0
 diag=['ADAPTIVE_V1_POST_OUTCOME_CAUSAL_GATE_DECOMPOSITION_V1.json','ADAPTIVE_V1_BREAK_EVEN_RATIO_DIAGNOSTIC_V1.json','ADAPTIVE_V1_FRICTION_BOUND_SEVERITY_AUDIT_V1.json','ADAPTIVE_V1_FROZEN_COST_STRESS_LADDER_RESULT_V1.json','ADAPTIVE_V1_COST_COVERAGE_GAP_DIAGNOSTIC_V1.json']
 missing=['CTRADER_CLIENT_ID','CTRADER_CLIENT_SECRET','CTRADER_REFRESH_TOKEN','CTRADER_EXPECTED_ACCOUNT_ID']
 blocker={'status':'PENDING_USER_SECURITY_ACTION','auth_proven':False,'exact_missing_secret_names':missing,'presence_verified_in_machine_side_actions':True,'presence_source_head':'5aab072e13aa2198b70070fc3ca87a0eda57e67d','presence_run_id':37455958290,'presence_job_id':112243506452,'presence_artifact_id':11409377773,'probe_result':'ALL_FOUR_EMPTY_ENVIRONMENT_VALUES;BOOLEAN_ONLY_NO_SECRET_VALUE_INSPECTION','broker_contact':False,'orders_placed':False,'market_history_acquired':False,'token_refresh_attempted':False,'oauth_reauthorization_required':'IF_NO_EXISTING_VALID_ACCOUNTS_ONLY_REFRESH_TOKEN;CANNOT_DETERMINE_FROM_EMPTY_REPOSITORY_SECRET','scope':'accounts ONLY;SCOPE_TRADE HARD_REJECTED BEFORE_ACCOUNT_AUTH','account_fingerprint_sha256':'b8bd610d0fe4395264e04bad98284c716d4b9d32fb46ce3ae6a2a9a1fd619636','secrets_location':'https://github.com/mariancradulescu/mxm-quant-greenfield/settings/secrets/actions','oauth_location':'https://openapi.ctrader.com/apps','minimal_user_steps':[{'step':1,'action':'Use existing approved cTrader app credentials. If no valid accounts-only token exists, open that app Playground, choose accounts scope and authorize intended Pepperstone Europe LIVE account. No trading scope.'},{'step':2,'action':'Enter client ID, client secret, accounts-only refresh token and exact ctidTraderAccountId (not trader login) directly as the four named repository Actions secrets. Never share values in chat.'},{'step':3,'action':'For a safe tiny auth proof without consuming the refresh token, also enter the access token from the SAME accounts-only Playground response as CTRADER_ACCESS_TOKEN. This is an additional temporary credential, not one of the four already-probed missing names.'},{'step':4,'action':'Report only that the secrets were saved. Agent pushes a hash-bound auth-only arm; user does not run/edit/debug workflows.'}],'additional_tiny_proof_credential':'CTRADER_ACCESS_TOKEN;NOT_PROBED_THIS_TASK;ALLOWS_AUTH_WITHOUT_REFRESH_ROTATION','after_security_action':'MACHINE_PUSH_OF_HASH_BOUND_AUTH_ONLY_ARM;ApplicationAuth;GetAccountList;SCOPE_VIEW_CHECK;FINGERPRINT_AND_LIVE_MATCH;AccountAuth;Trader_AND_EUR_ASSET_VERIFICATION;NO_HISTORY_ORDERS_OR_REFRESH','refresh_rotation':{'status':'PRIVATE_ATOMIC_LOCAL_CHECKPOINT_ADAPTER_PREPARED_NOT_DEPLOYED_OR_PROVEN','path':'adaptive_competition/private_token_checkpoint_v1.py','hosted_actions_refresh':'FORBIDDEN_UNTIL_DURABLE_PRIVATE_CHECKPOINT_IS_PROVISIONED_AND_AUDITED','local_atomicity':'0700_PARENT_0600_STATE_EXCLUSIVE_LOCK_FSYNC_ATOMIC_REPLACE','distributed_atomicity':'NOT_CLAIMED;REMOTE_ROTATION_TO_LOCAL_DURABILITY_CRASH_WINDOW_REQUIRES_RECOVERY_DESIGN;NO_UNATTENDED_REFRESH_AUTHORIZED'},'prepared_auth_allowlist':['ProtoOAApplicationAuthReq','ProtoOAGetAccountListByAccessTokenReq','ProtoOAAccountAuthReq','ProtoOATraderReq','ProtoOAAssetListReq'],'no_user_github_operator_requirement':True}
 save('MACHINE_SIDE_READ_ONLY_AUTH_USER_ACTION_BLOCKER_V1.json',blocker)
 audit={'status':'POST_OUTCOME_CAUSAL_DIAGNOSTIC_COMPLETE_PENDING_SECURITY_ACTION_AND_INDEPENDENT_AUDIT','exact_reconciled_start_head':BASE,'exact_historical_policy_hash':gate['exact_policy_spec_hash'],'exact_historical_raw_result_hash':gate['historical_raw_result_sha256'],'historical_raw_result_byte_identical':True,'frozen_spec_byte_identical':True,'budget_byte_identical':True,'search_budget':{'total':84,'used':21,'remaining':63,'refunds':0,'economic_outcomes_opened':29},'outer_policy_rerun':False,'new_economic_identity':False,'new_outcome':False,'diagnostic_artifact_hashes':{p:hashlib.sha256((STATE/p).read_bytes()).hexdigest() for p in diag},'refined_classification':CLASS,'previous_classification':'ECONOMIC_SCOPE_COST_LIMITED','previous_interpretation_preserved_as_historical':True,'causal_reassessment':{'primary_measured_gate':'UNCERTAINTY_RELATIVE_TO_FROZEN_FORECAST_MAGNITUDE','forecast_heads_removed_by_uncertainty':counts['forecast_nonzero_count']-counts['uncertainty_adjusted_positive_count'],'fraction_removed_by_uncertainty':1-counts['uncertainty_adjusted_positive_count']/counts['forecast_nonzero_count'],'admissible_positive_heads_eliminated_by_spread':125,'positive_cost_unresolved_heads':6997,'positive_cost_supported_conversion_unresolved_heads':2,'positive_cost_unresolved_zero_initialized_uncertainty_heads':6980,'positive_cost_unresolved_nonzero_uncertainty_heads':17,'initialization_caveat':'SE_ZERO_UNDER_LT24_MATURE_SAMPLES_IS_DEFAULT_STATE_NOT_ZERO_TRUE_UNCERTAINTY;THIS_DIAGNOSTIC_DOES_NOT_RESCUE_OR_MODIFY_V1','commission_delay_incremental_elimination_after_spread':0,'cost_coverage_not_sufficient_as_sole_causal_label':True,'counterfactual_limits':'FROZEN_GATE_ARITHMETIC_ESTABLISHED;NOT_INTRINSIC_ALPHA_ABSENCE_OR_OPTIMALITY_OF_UNCERTAINTY_COST_LAWS;NO_POLICY_RESCUE'},'historical_telemetry_clarification':'gross_positive_opportunity_count IS abs(mu)>0 NONZERO_FORECAST_COUNT;NOT_28.5_MILLION_PROVEN_ECONOMIC_OPPORTUNITIES','inner_selection':'CONFIGURATIONS_0_AND_1_BOTH_ZERO_ENTRIES_EUR200_UTILITY0;CONFIG0_SELECTED_BY_FROZEN_COMPACTNESS_TIE_BREAK;NO_LINEAR_ECONOMIC_SUPERIORITY_CLAIM','forecast_IC':'HISTORICAL_VALUES_PRESERVED;NOT_USED_AS_CAUSAL_CLASSIFICATION_SHORTCUT','cost_model_limit':'DISCOVERY_SCENARIO:2X_PREFIX_MAX_SPREAD_CURRENT_TYPED_COMMISSION_X2_QUARTER_LAST_BAR_RANGE_DELAY_EACH_SIDE;NOT_EXACT_HISTORICAL_EXECUTION_COST','statistical_significance_certified':False,'realizable_edge_certified':False,'auth_status':'PREPARED_NOT_PROVEN_MISSING_FOUR_SECRETS','auth_user_action_blocker_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_USER_ACTION_BLOCKER_V1.json','triad_v7_parked_unchanged':True,'protected_forward_opened':False,'confirmation_opened':False,'orders_placed':False,'history_acquired':False,'next_action':NEXT}
 save('ADAPTIVE_V1_INDEPENDENT_AUDIT_RESPONSE_V1.json',audit)
 p=STATE/'ADAPTIVE_COMPETITION_CURRENT_STATE.json';j=json.loads(p.read_text());j.update({'historical_classification':j.get('historical_classification',j['classification']),'classification':CLASS,'diagnostic_classification':CLASS,'diagnostic_status':'POST_OUTCOME_READ_ONLY_COMPLETE','diagnostic_audit_response_ref':'adaptive_competition/state/ADAPTIVE_V1_INDEPENDENT_AUDIT_RESPONSE_V1.json','machine_side_auth_status':'PREPARED_NOT_PROVEN_MISSING_FOUR_SECRETS','next_action':NEXT});save(p.name,j)
 p=STATE/'ADAPTIVE_COMPETITION_AUTHORITY_V1.json';j=json.loads(p.read_text());j.update({'historical_economic_replay_authorized':j.get('historical_economic_replay_authorized',j['economic_replay_authorized']),'economic_replay_authorized':False,'current_operation':NEXT,'post_outcome_diagnostic_complete':True,'new_economic_outcome_authorized':False});save(p.name,j)
 p=STATE/'MACHINE_SIDE_READ_ONLY_RESEARCH_AUTH_FOLLOWUP_STATE.json';j=json.loads(p.read_text());j.update({'status':'PREPARED_NOT_PROVEN_PENDING_USER_SECURITY_ACTION','secret_provisioning_verified':False,'secret_names_presence_checked':True,'secret_values_provisioned':False,'auth_proven':False,'next_gate':NEXT,'user_action_blocker_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_USER_ACTION_BLOCKER_V1.json','deterministic_preflight_code_ref':'adaptive_competition/read_only_auth_preflight_v1.py','workflow_ref':'.github/workflows/adaptive-read-only-auth-preflight-v1.yml','refresh_rotation_status':'PRIVATE_ATOMIC_LOCAL_ADAPTER_PREPARED_NOT_DEPLOYED_UNATTENDED_REFRESH_LOCKED','tiny_preflight_access_token_strategy':'SEPARATE_TEMPORARY_CTRADER_ACCESS_TOKEN_DIRECT_SECRET;NO_REFRESH_ON_HOSTED_ACTIONS'});save(p.name,j)
 p=ROOT/'CURRENT_STATE.json';j=json.loads(p.read_text());j.update({'next_action':NEXT,'phase':NEXT,'adaptive_v1_diagnostic_classification':CLASS});p.write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
 p=ROOT/'research_core_v4/state/V4_STATE.json';j=json.loads(p.read_text());j.update({'current_next_action_type':NEXT,'next_action':NEXT,'status':'ADAPTIVE_V1_POST_OUTCOME_CAUSAL_DIAGNOSTIC_COMPLETE_PENDING_USER_SECURITY_ACTION','adaptive_v1_diagnostic_classification':CLASS});p.write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
if __name__=='__main__':main()
