"""Interpret/publish the single V3 result and stop. No network or credential access."""
import json,hashlib
from pathlib import Path
from .read_only_auth_preflight_v3 import validate_safe,GATES,FORBIDDEN_FLAGS
S=Path('adaptive_competition/state')
def save(path,j):Path(path).write_text(json.dumps(j,sort_keys=True,indent=2)+'\n')
def main():
 r=json.loads((S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V3.json').read_text());validate_safe(r)
 assert r['execution_head']=='772dfaef00152893a59d63847deb873a276082c6'
 next_action='PENDING_INDEPENDENT_AUDIT_OF_MACHINE_SIDE_READ_ONLY_AUTH_V3_BEFORE_ANY_MARKET_DATA_ACQUISITION' if r['auth_proven'] else 'PENDING_INDEPENDENT_AUDIT_OF_MACHINE_SIDE_READ_ONLY_AUTH_V3_FAILURE'
 p=S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V3_VALIDATION.json';v=json.loads(p.read_text());v.update({'status':'PASS_POST_AUTH_AUTHENTIC_ARTIFACT_AND_HISTORICAL_INTEGRITY_VALIDATION','auth_attempt_executed':True,'auth_status':r['status'],'safe_reason':r['safe_reason'],'authentic_result_sha256':hashlib.sha256((S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V3.json').read_bytes()).hexdigest(),'downloaded_actions_artifact_sha256':'5e3ef9154c26272f17acc00a8ff908ab0e4d0495539a8ebc1ea9e116fe2014de','downloaded_artifact_json_byte_identical':True,'artifact_object_equals_job_safe_result':True,'safe_schema_verified':True,'preauth_source_head':r['exact_source_head'],'execution_head':r['execution_head'],'result_persisted_before_interpretation_head':'2e2edae2b906f516c1931cd4eb9661a7eedb5276','preauth_bounded_ci_run_id':37467180631,'auth_run_id':37467282857,'auth_job_id':112281423641,'auth_artifact_id':11414842187,'auth_workflow_conclusion':'success','authenticated_attempt_count':1,'authenticated_retries':0,'precontact_workflow_failure_count':1,'precontact_failure_authenticated_attempts':0,'local_unit_test_count':23,'three_runtime_secrets_present':True,'refresh_token_presence_confirmed_without_auth_process_inheritance':True,'zero_forbidden_activity_flags':{k:r[k] for k in FORBIDDEN_FLAGS},'transport_closed':r['transport_closed'],'post_run_gate_results':{k:r[k] for k in GATES},'configuration_field_presence':{k:r[k] for k in ['account_type_field_explicit','margin_mode_field_explicit','swap_free_field_explicit']},'broker_text_used_as_identity_or_region_gate':False,'historical_account_identity_authority_used':True,'V2_failure_semantics':'METHOD_DEFECT_NOT_ACCOUNT_IDENTITY_FAILURE;V2_PRESERVED_UNCHANGED','current_account_configuration_proven':r['auth_proven'],'no_new_economic_identity':True,'budget_consumed':0,'post_validation_script_sha256':hashlib.sha256(Path('adaptive_competition/validate_read_only_auth_v3_result.py').read_bytes()).hexdigest(),'next_action':next_action});save(p,v)
 p=S/'MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V3_AUTHORITY.json';j=json.loads(p.read_text());j.setdefault('frozen_preauth_authority_sha256',hashlib.sha256(p.read_bytes()).hexdigest());j.update({'preauth_status':j.get('preauth_status',j['status']),'status':r['status'],'attempt_completed':True,'exact_source_head':r['exact_source_head'],'execution_head':r['execution_head'],'authenticated_attempt_count':1,'authenticated_retries':0,'result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V3.json','result_sha256':v['authentic_result_sha256'],'validation_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V3_VALIDATION.json','next_action':next_action,'post_result_contact_authorized':False});save(p,j)
 p=S/'ADAPTIVE_COMPETITION_CURRENT_STATE.json';j=json.loads(p.read_text());j.update({'machine_side_auth_status':r['status'],'machine_side_auth_v3_result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V3.json','machine_side_auth_v3_safe_reason':r['safe_reason'],'machine_side_auth_v3_attempt_count':1,'next_action':next_action});save(p,j)
 p=S/'ADAPTIVE_COMPETITION_AUTHORITY_V1.json';j=json.loads(p.read_text());j['current_operation']=next_action;save(p,j)
 p=S/'MACHINE_SIDE_READ_ONLY_RESEARCH_AUTH_FOLLOWUP_STATE.json';j=json.loads(p.read_text());j.setdefault('historical_V2_result_ref',j['result_ref']);j.setdefault('historical_V2_result_sha256',j['result_sha256']);j.update({'status':r['status'],'auth_proven':r['auth_proven'],'secret_provisioning_verified':True,'secret_names_presence_checked':True,'secret_values_provisioned':True,'secret_values_inspected':False,'runtime_required_secret_names':['CTRADER_CLIENT_ID','CTRADER_CLIENT_SECRET','CTRADER_ACCESS_TOKEN'],'required_prospective_secret_names':['CTRADER_CLIENT_ID','CTRADER_CLIENT_SECRET','CTRADER_ACCESS_TOKEN','CTRADER_REFRESH_TOKEN'],'expected_account_id_secret_required':False,'account_identity':'UNIQUE_FROZEN_HISTORICAL_FINGERPRINT_MATCH;ACCEPTED_AUTHORITY_BINDS_PEPPERSTONE_EUROPE_LIVE;BROKER_TEXT_NOT_USED','historical_identity_authority_ref':'research_core_v3/state/ACCOUNT_IDENTITY_REBIND_ACCEPTANCE_V1.json','user_security_action_required_now':False,'current_user_security_steps':[],'deterministic_preflight_code_ref':'adaptive_competition/read_only_auth_preflight_v3.py','workflow_ref':'.github/workflows/adaptive-read-only-auth-preflight-v3.yml','current_authority_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_V3_AUTHORITY.json','result_ref':'adaptive_competition/state/MACHINE_SIDE_READ_ONLY_AUTH_PREFLIGHT_RESULT_V3.json','result_sha256':v['authentic_result_sha256'],'next_gate':next_action,'broker_contact_this_task':True,'historical_acquisition_this_task':False,'refresh_token_present':True,'refresh_token_used':False,'refresh_attempted':False,'tiny_preflight_access_token_strategy':'CTRADER_ACCESS_TOKEN_ONLY_NO_REFRESH_NO_EXPECTED_ACCOUNT_ID','preflight_failure_safe_reason':r['safe_reason'],'deterministic_preflight_sequence':['ApplicationAuth','GetAccountListByAccessToken','Require explicit SCOPE_VIEW','Unique accepted historical fingerprint match and LIVE','AccountAuth same account','TraderReq same account;HEDGED/MAX/non-swap-free','AssetListReq same account;unique EUR deposit asset','Close transport'],'current_account_configuration_proven':r['auth_proven'],'future_acquisition_authorized':False,'authenticated_attempt_count_V3':1,'authenticated_retries_V3':0});save(p,j)
 p=Path('CURRENT_STATE.json');j=json.loads(p.read_text());j.update({'next_action':next_action,'phase':next_action,'machine_side_auth_v3_status':r['status']});save(p,j)
 p=Path('research_core_v4/state/V4_STATE.json');j=json.loads(p.read_text());j.update({'current_next_action_type':next_action,'next_action':next_action,'status':'MACHINE_SIDE_READ_ONLY_AUTH_V3_PROVEN_PENDING_INDEPENDENT_AUDIT' if r['auth_proven'] else 'MACHINE_SIDE_READ_ONLY_AUTH_V3_FAILED_CLOSED_PENDING_INDEPENDENT_AUDIT','machine_side_auth_v3_status':r['status']});save(p,j)
if __name__=='__main__':main()
