"""One prospective governance correction; never change historical scientific records."""
import json,pathlib,hashlib
R=pathlib.Path('.');p=R/'research_core_v4/state/V4_STATE.json';d=json.loads(p.read_bytes());old={k:d.get(k) for k in ['status','next_action','stop_boundary','next_information_source_selection']}
d['status']='DISCOVERY_PROTOCOL_INFERENCE_BLOCKED'
d['next_action']='REMEDIATE_DISTINCT_INFERENCE_ONLY_NO_MARKET_OR_ACQUISITION'
d['stop_boundary']='STOP_BEFORE_ANY_MARKET_RESPONSE_ACQUISITION_CONFIRMATION_OR_TRADING;PROTOCOL_CERTIFICATION_REQUIRED_BEFORE_NEXT_ACTION_RERANK'
d['next_information_source_selection_status']='HISTORICAL_V5_PENDING_VALIDATED_POST_PROTOCOL_RERANK_NOT_ACTION_AUTHORITY'
d['current_next_action_type']=None
a={'schema':'mxm.v4.discovery-authority-state-hardening.v1','starting_head':'da3180ee67b2c93c6b9d57785e9bb85e19e89088','prior_top_level':old,'new_top_level':{k:d[k] for k in ['status','next_action','stop_boundary','next_information_source_selection_status','current_next_action_type']},'historical_V5_selection_ref':d['next_information_source_selection'],'historical_V5_not_current_market_action_authority':True,'depth_nested_plan_preserved':True,'depth_requirement_sha256':hashlib.sha256((R/'research_core_v4/state/BROKER_DEPTH_SIZE_INFORMATION_REQUIREMENT_V1.json').read_bytes()).hexdigest(),'failed_candidates_unchanged':['DAILY_HAC10_HOLM','WEEKLY_HAC2_HOLM'],'new_acquisition_authorized':False,'real_response_authorized':False,'candidate_frozen_count':0,'protected_forward_opened':False,'confirmation_opened':False,'broker_contacts':0,'historical_requests':0,'orders':0,'Runtime_V2':'READ_ONLY','legacy_audit_validator_scope':'audit_v2/validate_checkpoint_v1.py is bound to historical da3180ee state and should be run only on that immutable checkpoint; successor validation below handles explicitly allowed governance fields. Historical validator is not changed.'}
q=R/'research_core_v4/state/DISCOVERY_AUTHORITY_STATE_HARDENING_V1.json';q.write_text(json.dumps(a,sort_keys=True,indent=2)+'\n');d['discovery_authority_hardening_ref']=str(q);d['discovery_authority_hardening_sha256']=hashlib.sha256(q.read_bytes()).hexdigest();p.write_text(json.dumps(d,sort_keys=True,indent=2)+'\n')
