"""Apply frozen gates to already persisted raw synthetic evidence; no simulation."""
import json,pathlib,hashlib
R=pathlib.Path('.');B=R/'research_core_v4/inference_v2'
p=B/'JBW_MAXT_CERTIFICATION_PLAN_V1.json';d=json.loads(p.read_bytes());rpath=B/'JBW_MAXT_RAW_SYNTHETIC_RESULT_V1.json';r=json.loads(rpath.read_bytes())
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
assert h(p)==r['plan_sha256'] and h(B/'joint_block_wild_maxt_v1.py')==d['implementation_sha256']==r['implementation_sha256'];assert r['interpretation_present'] is False and r['invariants']['pass']
rows=[]
for case in d['null_cases']:
 assert set(r['null'][case]['configurations'])==set(d['null_configurations'])
 for cfg in d['null_configurations']:
  m=r['null'][case]['configurations'][cfg];sign=m['any_false_significance'];lead=m['any_false_complete_lead'];assert sign['trials']==lead['trials']==d['null_trials_per_case'];assert lead['rejections']<=sign['rejections']
  rows.append({'case':case,'configuration':cfg,'any_false_significance':sign,'any_false_complete_lead':lead,'false_context_selection':m['false_context_selection'],'pass':sign['wilson'][1]<=d['declared_FWER_ceiling'] and lead['wilson'][1]<=d['declared_FWER_ceiling']})
mdi={};power_complete=True
for case in d['null_cases']:
 mdi[case]={}
 for alt,spec in d['power_alternatives'].items():
  curves=r['power'][case][alt];assert set(curves)=={str(e) for e in d['power_effects_daily_score_SD']}
  for entry in curves.values():
   for metric in ['any_target_lead','all_target_leads','old_universal_complete']:assert entry[metric]['trials']==d['power_trials_per_case']
   assert set(entry['per_target_leaf'])==set(spec)
  def first(metric,key=None):
   ee=[e for e in d['power_effects_daily_score_SD'] if (curves[str(e)][metric][key] if key is not None else curves[str(e)][metric])['wilson'][0]>=d['power_target']];return min(ee) if ee else None
  mdi[case][alt]={'any_target_grid_MDE':first('any_target_lead'),'all_target_grid_MDE':first('all_target_leads'),'per_target_leaf_grid_MDE':{k:first('per_target_leaf',k) for k in spec},'old_universal_grid_MDE':first('old_universal_complete')}
pass_error=all(x['pass'] for x in rows)
a={'schema':'mxm.v4.joint-block-wild-maxt-certification-interpretation.v1','method':d['method'],'raw_result_commit':'76c145ff3476f25099cb11a05d7ebba9caf210cb','plan_commit':'d888440fe17fa669f4d881f36b5b416b2edfb4d6','plan_sha256':h(p),'implementation_sha256':r['implementation_sha256'],'raw_result_sha256':h(rpath),'strong_FWER_cases':rows,'all44_strong_FWER_gates_pass':pass_error,'power_characterization_complete':power_complete,'power_target':d['power_target'],'minimum_grid_effects_daily_score_SD':mdi,'invariant_pass':True,'no_post_result_tuning':True,'failed_candidates_rescued':False,'classification':'PASS_DECLARED_SYNTHETIC_COMPLETE_PROCEDURE_ENVELOPE_ONLY' if pass_error else 'UNCERTIFIED_FROZEN_ERROR_GATE_FAILED','universal_validity_claimed':False,'real_mechanism_or_geometry_certified':False,'gap_support_warning':{'all12_supported_null_trials':r['null']['contiguous_gaps']['all_leaf_support_trials'],'trials':d['null_trials_per_case'],'interpretation':'No simulated contiguous-gap path supports ALL12 leaves. Some individual leaves remain supported. FWER measured for the complete support-screened procedure; this is not full-family inference certification conditional on all12 supported. Localized gap power plateaus below80percent and grid MDE is unavailable. Preserve support failure, no relaxation.'},'presentation_correction':'Before publication, explicitly order named G/P1/P2/P3 table columns rather than JSON lexical iteration; raw named configurations and all values unchanged.', 'precision_note':'FixedRademacherbank conditional certification;9216 independent generated paths percase, four null configurations share each path.44configurations are not44 independent runs. Wilson simultaneous rule uses z3.5.','theory_limitations':['Finite-envelope empirical control, not finite-sample distribution-free guarantee','Fixed15 potential calendar clusters; more than declared dependence/geometry needs new prospective calibration','Exogenous synthetic masks; endogenous censoring and market latency unsupported','Actual horizon-overlap, nuisance-prefix estimation, selected cohort breadth and mechanism-specific stability require exact-geometry tests before responses','Abstract two-of-three stability exemplar is not a universal production breadth/stability rule'],'protocol_freeze_prerequisites_satisfied_for_prospective_method_framework':bool(pass_error and power_complete),'broker_contacts':0,'historical_requests':0,'new_market_responses':0,'orders':0}
(B/'JBW_MAXT_CERTIFICATION_INTERPRETATION_V1.json').write_text(json.dumps(a,sort_keys=True,indent=2)+'\n')
lines=['# Joint block wild maxT certification — full synthetic report','','This report applies the frozen law to raw results already committed at76c145ff3476f25099cb11a05d7ebba9caf210cb. No simulations or tuning are performed by interpretation.','',f"Result: **{a['classification']}**. All44 strong-FWER gates pass; power characterization complete. This is a prospective method framework, not a market mechanism or economic certification.",'','Plan SHA256: `'+a['plan_sha256']+'`','Implementation SHA256: `'+a['implementation_sha256']+'`','Raw result SHA256: `'+a['raw_result_sha256']+'`','','## Every global and partial-null result','','N=9216 percase, z=3.5 simultaneous Wilson. Each cell: point FWER% / simultaneous upper%. Complete-lead counts equal the significance counts in this run; both were checked. Configurations: G=global; P1=context0/horizon0nonnull; P2=context0/horizons0,1,2nonnull including opposite signs; P3=five nonnull leaves distributed across threecontexts with remaining truenulls.','', '| Case | G | P1 | P2 | P3 | All12support |','|---|---:|---:|---:|---:|---:|']
for case in d['null_cases']:
 vals=[]
 for cfg in ['global_null','one_context_one_horizon_nonnull','one_context_multiple_horizons_nonnull','multiple_contexts_remaining_true_nulls']:
  m=r['null'][case]['configurations'][cfg]['any_false_significance'];vals.append(f"{100*m['rate']:.4f} / {100*m['wilson'][1]:.4f}")
 lines.append('|'+case+'|'+'|'.join(vals)+'|'+str(r['null'][case]['all_leaf_support_trials'])+' /9216|')
lines+=['','## Minimum detectable grid effects','','Daily marginal score SD, target LOWER95Wilson power>=.80. No interpolation, bps or profit conversion. Outside grid means unavailable, not infinite effect or scientific null.','', '| Case | Local+ | Local− | Heterogeneous ANY / ALL | Samehorizon allcontext ANY / ALL |','|---|---:|---:|---:|---:|']
def fmt(x):return 'outside grid / support-limited' if x is None else str(x)
for case in d['null_cases']:
 m=mdi[case];lines.append('|'+case+'|'+fmt(m['localized_positive']['any_target_grid_MDE'])+'|'+fmt(m['localized_negative']['any_target_grid_MDE'])+'|'+fmt(m['heterogeneous_context_directions']['any_target_grid_MDE'])+' / '+fmt(m['heterogeneous_context_directions']['all_target_grid_MDE'])+'|'+fmt(m['all_contexts_same_horizon_secondary']['any_target_grid_MDE'])+' / '+fmt(m['all_contexts_same_horizon_secondary']['all_target_grid_MDE'])+'|')
lines+=['','## Full power curves','','N=2048 percase. Every displayed power is complete selected-lead power. In each cell, percent point [lower,upper]95Wilson. For multicontext alternatives both ANY and ALL prespecified targets are shown; target-specific uncertainty is also retained in raw JSON. Old universal comparator uses identical210day paths, immutable old() law and synthetic masks; no failedcandidate detector is executed.','','Contiguous-gap warning: all12supported=0/9216, and localized power never reaches80percent. This is a support-limited procedure, not proof of reliable full-family inference through these gaps. Do not use this case to claim powered discovery or loosen support.']
def powerstr(x):return f"{100*x['rate']:.2f} [{100*x['wilson'][0]:.2f},{100*x['wilson'][1]:.2f}]"
for case in d['null_cases']:
 lines+=['','### '+case,'','| Effect | Local+ | Local− | Heterogeneous ANY / ALL | Allcontext ANY / ALL | Olduniversal local+ / allcontext |','|---|---|---|---|---|---|']
 for e in d['power_effects_daily_score_SD']:
  rr=r['power'][case];p=rr['localized_positive'][str(e)];n=rr['localized_negative'][str(e)];hh=rr['heterogeneous_context_directions'][str(e)];aa=rr['all_contexts_same_horizon_secondary'][str(e)];lines.append('|'+str(e)+'|'+powerstr(p['any_target_lead'])+'|'+powerstr(n['any_target_lead'])+'|'+powerstr(hh['any_target_lead'])+' / '+powerstr(hh['all_target_leads'])+'|'+powerstr(aa['any_target_lead'])+' / '+powerstr(aa['all_target_leads'])+'|'+powerstr(p['old_universal_complete'])+' / '+powerstr(aa['old_universal_complete'])+'|')
lines+=['','## Theory and unresolved applicability','','Null-centered joint block wild bootstrap-t approximates weak temporal dependence with a common multiplier for entire original calendar blocks and all leaves; maxT pays all12 context/horizon choices, bothdirections. Studentization is recomputed in eachdraw. This is a finite certified stress envelope, not exact general strongFWER. Nominal.025 leaves headroom to the unchanged.05ceiling.','', 'Normal_weak and common_factors share the baseline innovation-factor geometry; strong_common_factors is a genuinely stronger .80global/.15context/.05idiosyncratic, rho.25 stress. Normal_weak baseline rho.1. No duplicated baseline is used as a substitute for stronger stress.','', 'Constant nonnull shifts leave centered covariance and bootstrap reference invariant; this is mechanically verified. Partial-null certification establishes the declared shift alternatives and remaining true-null decisions, not arbitrary mean/covariance-changing market alternatives.','', 'Discovery/local/context/horizon/stability are evaluated in the complete simulated decision. The proposed framework must require separate prospectively frozen exact-mechanism support, prefix estimation, horizonoverlap, censoring, selection, stability/breadth and jointgeometry tests. No market response, confirmation, economic certification or depth acquisition is authorized by these results.']
(B/'JBW_MAXT_FULL_SYNTHETIC_REPORT_V1.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'error_pass':pass_error,'power_characterization_complete':power_complete,'worst':max(rows,key=lambda x:x['any_false_significance']['wilson'][1]),'gap_support_warning':a['gap_support_warning']}))
