from pathlib import Path
import hashlib,json,gzip
from decimal import Decimal
from one_sided_numerical_certificate_v1 import certify
P=Path(__file__).resolve().parent
raw=json.loads(gzip.decompress((P/'ORACLE_FIXTURE_RAW_V1.json.gz').read_bytes()));rows=[]
for f in raw['fixtures']:
 r=certify(f['X'],f['D'],f['Jacobi'],f['oracles']['100'],f['oracles']['160']);r.update(id=f['id'],n=f['n'],Python_accept=f['historical_Python']['accepted'],input_sha256=f['input_sha256'],candidate_output_bit_identical_to_V4=f['candidate_output_bit_identical_to_V4'])
 if not f['candidate_output_bit_identical_to_V4']:r['pass']=False;r['failures'].append('KERNEL_REEXECUTION_CHANGED')
 rows.append(r)
s={'schema':'TRIAD_V6_FIXTURE_GATE_RESULT_V1','raw_sha256':hashlib.sha256((P/'ORACLE_FIXTURE_RAW_V1.json.gz').read_bytes()).hexdigest(),'fixtures':537,'oracle_certified':sum(r['oracle_certified'] for r in rows),'oracle_mathematically_eligible':sum(r['oracle_certified'] and r['oracle_eligible'] for r in rows),'production_accepted':sum(r['production_accept'] for r in rows),'unsafe_production_accepts':sum(r['unsafe_accept'] for r in rows),'conservative_production_rejections':sum(r['conservative_rejection'] for r in rows),'threshold_ambiguity_rejections':sum(r['production_support']['threshold_ambiguous'] for r in rows),'maximum_accepted_normalized_RD_error':str(max((Decimal(r.get('normalized_RD_error','0')) for r in rows if r['production_accept']),default=Decimal(0))),'maximum_accepted_independent_orthogonality':max((r['production_support'].get('independent_orthogonality_error',0) for r in rows if r['production_accept']),default=0),'maximum_accepted_backward_error_eta':max((r['production_support'].get('backward_error_eta',0) for r in rows if r['production_accept']),default=0),'maximum_cross_precision_singular_relative':str(max((Decimal(r.get('cross_precision_singular_relative','0')) for r in rows),default=Decimal(0))),'maximum_cross_precision_RMS_relative':str(max((Decimal(r.get('cross_precision_RMS_relative','0')) for r in rows),default=Decimal(0))),'maximum_cross_precision_normalized_abs_eligible':str(max((Decimal(r.get('cross_precision_normalized_abs','0')) for r in rows if r['oracle_eligible']),default=Decimal(0))),'failed_fixtures':sum(not r['pass'] for r in rows),'all_pass':all(r['pass'] for r in rows),'actual_XD_audit_count':0,'full_null_trials':0,'full_power_trials':0,'rows':rows}
b=(json.dumps(s,indent=2,sort_keys=True)+'\n').encode();(P/'FIXTURE_GATE_RESULT_V1.json.gz').write_bytes(gzip.compress(b,mtime=0));(P/'FIXTURE_GATE_SUMMARY_V1.json').write_text(json.dumps({k:v for k,v in s.items() if k!='rows'},indent=2,sort_keys=True)+'\n');print(json.dumps({k:v for k,v in s.items() if k!='rows'}));print(json.dumps({'first_failures':[r for r in rows if not r['pass']][:4]}))
