// Synthetic quoted-log-return paths only. No broker, file price loader or network.
// Fixed geometry comes from authoritative identities and timestamp masks.
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>
using namespace std;
constexpr int A=75,R=107,C=3,H=4,T=44,DAYS=210,K=8,BARS=146,L=13;
struct Geo {double load[A][L],scale[A],rs[R];int leg[R][3],sgn[R][3],rc[R],target[R],tc[T],ta[T];bool causal[DAYS][K][R],complete[DAYS][K][C][H];int signs[1023][15];};
struct Output {double daily[DAYS][12],loo[DAYS][T][H];bool valid[DAYS][12];int numerical;};
struct Decisions{array<bool,12> reject,lead;bool support;};
void loadgeo(Geo &g,const string &path){ifstream f(path);if(!f)throw runtime_error("geometry file missing");for(int a=0;a<A;a++){f>>g.scale[a];for(int j=0;j<L;j++)f>>g.load[a][j];}for(int r=0;r<R;r++){f>>g.rc[r]>>g.target[r]>>g.rs[r];for(int j=0;j<3;j++)f>>g.leg[r][j]>>g.sgn[r][j];}for(int t=0;t<T;t++)f>>g.tc[t]>>g.ta[t];int x;for(int d=0;d<DAYS;d++)for(int k=0;k<K;k++)for(int r=0;r<R;r++){f>>x;g.causal[d][k][r]=x;}for(int d=0;d<DAYS;d++)for(int k=0;k<K;k++)for(int c=0;c<C;c++)for(int h=0;h<H;h++){f>>x;g.complete[d][k][c][h]=x;}for(int b=0;b<1023;b++)for(int d=0;d<15;d++)f>>g.signs[b][d];if(!f)throw runtime_error("geometry format");}
double dot3(const double *a,const double *b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
bool inv3(double a[3][3],double z[3][3]) {double det=a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])+a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);if(!(det>1e-12))return false;z[0][0]=(a[1][1]*a[2][2]-a[1][2]*a[2][1])/det;z[0][1]=(a[0][2]*a[2][1]-a[0][1]*a[2][2])/det;z[0][2]=(a[0][1]*a[1][2]-a[0][2]*a[1][1])/det;z[1][0]=z[0][1];z[1][1]=(a[0][0]*a[2][2]-a[0][2]*a[2][0])/det;z[1][2]=(a[0][2]*a[1][0]-a[0][0]*a[1][2])/det;z[2][0]=z[0][2];z[2][1]=z[1][2];z[2][2]=(a[0][0]*a[1][1]-a[0][1]*a[1][0])/det;return true;}
struct Clock {int n,ids[T];double X[T][3],F[T],rd[T],normalized[T],inv[3][3],lev[T],r2;bool ok;};
Clock clockfit(const Geo&g,int day,int k,int c,const double ret[BARS][A]) {Clock x{};double past[A],last[A];int q=12+12*k;for(int a=0;a<A;a++){past[a]=0;for(int b=q-11;b<=q;b++)past[a]+=ret[b][a];last[a]=ret[q][a];}double df[T]={},cnt[T]={};int nr=0;
for(int r=0;r<R;r++)if(g.rc[r]==c&&g.causal[day][k][r]){double f=0;for(int j=0;j<3;j++)f+=g.sgn[r][j]*past[g.leg[r][j]];f=max(-3.,min(3.,f/g.rs[r]));df[g.target[r]]+=f;cnt[g.target[r]]++;nr++;}
int declared=0;for(int t=0;t<T;t++)if(g.tc[t]==c){declared++;if(cnt[t]>0){int n=x.n++;x.ids[n]=t;int a=g.ta[t];x.X[n][0]=1;x.X[n][1]=last[a]/g.scale[a];x.X[n][2]=past[a]/g.scale[a];x.F[n]=df[t]/cnt[t];}}
int allr=0;for(int r=0;r<R;r++)if(g.rc[r]==c)allr++;if(x.n<max(5,(declared+1)/2)||nr<(allr+1)/2)return x;
// Normalize control columns without changing the declared span.
for(int j=1;j<3;j++){double s=0;for(int i=0;i<x.n;i++)s+=x.X[i][j]*x.X[i][j];s=sqrt(s/x.n);if(!(s>1e-12))return x;for(int i=0;i<x.n;i++)x.X[i][j]/=s;}
double gram[3][3]={},rhs[3]={};for(int i=0;i<x.n;i++)for(int j=0;j<3;j++){rhs[j]+=x.X[i][j]*x.F[i];for(int l=0;l<3;l++)gram[j][l]+=x.X[i][j]*x.X[i][l];}if(!inv3(gram,x.inv))return x;double beta[3];for(int j=0;j<3;j++)beta[j]=dot3(x.inv[j],rhs);x.r2=0;double orth[3]={};for(int i=0;i<x.n;i++){x.rd[i]=x.F[i]-dot3(x.X[i],beta);x.r2+=x.rd[i]*x.rd[i];for(int j=0;j<3;j++)orth[j]+=x.X[i][j]*x.rd[i];double y[3];for(int j=0;j<3;j++)y[j]=dot3(x.inv[j],x.X[i]);x.lev[i]=dot3(x.X[i],y);}if(!(x.r2/x.n>=1e-20))return x;for(int j=0;j<3;j++)if(abs(orth[j])>1e-7)throw runtime_error("projection orthogonality error");for(int i=0;i<x.n;i++)x.normalized[i]=x.rd[i]/sqrt(x.r2/x.n);x.ok=true;return x;}
double v12(double rho){double v=12;for(int k=1;k<12;k++)v+=2*(12-k)*pow(rho,k);return v;}
void basepaths(const Geo &g,int which,mt19937_64&rg,vector<double>&base){normal_distribution<double> norm(0,1);gamma_distribution<double> gam(2.5,2);gamma_distribution<double> skewgam(1.5,2);for(int day=0;day<DAYS;day++){double rho=which==1?.25:which==2?.5:which==3?pow(.5,1./288):.1;if(which==9)rho=day<105?.1:.5;if(which==10)rho=day<105?.25:.5;double factor[L];double prev[A]={};double dailyvol=which==6?exp(.45*norm(rg)-.2025):1.;double regvol=which==10?(day<105?.6:1.3):1.;for(int b=0;b<BARS;b++){for(int j=0;j<L;j++){double z=norm(rg);if(which==4)z*=sqrt(3./gam(rg));if(which==5)z=(skewgam(rg)-3)/sqrt(6.);factor[j]=z*dailyvol*regvol;}
for(int a=0;a<A;a++){double value=0,variance=0;for(int j=0;j<L;j++){double w=g.load[a][j];if(which==7)w*=j==0?4.:.4;if(which==8||which==10){double drift=which==8?(.25+1.5*day/209.):(day<105?.35:1.75);if(j>=5)w*=drift;if(j==0)w*=1.5;}value+=w*factor[j];variance+=w*w;}double scale=g.scale[a]/sqrt(v12(rho)*variance);double r=(b?rho*prev[a]:0)+(b?sqrt(1-rho*rho):1)*value*scale;prev[a]=r;base[(day*BARS+b)*A+a]=r;}}}}
double rhoFor(int which,int day){return which==1?.25:which==2?.5:which==3?pow(.5,1./288):which==9?(day<105?.1:.5):which==10?(day<105?.25:.5):.1;}
void compute(const Geo&g,const vector<double>&base,int which,const array<double,3>&delta,Output&out){out=Output{};int steps[4]={3,6,12,48};for(int day=0;day<DAYS;day++){double ret[BARS][A];copy(base.begin()+day*BARS*A,base.begin()+(day+1)*BARS*A,&ret[0][0]);Clock stored[K][C];double sum[12]={};int count[12]={};double ls[T][H]={};bool lok[T][H];for(int t=0;t<T;t++)for(int h=0;h<H;h++)lok[t][h]=true;
for(int k=0;k<K;k++){Clock fits[3];for(int c=0;c<C;c++){fits[c]=clockfit(g,day,k,c,ret);if(!fits[c].ok)out.numerical++;}
// Causal relational innovations are injected AFTER currentpredictor formation.
for(int c=0;c<C;c++)if(delta[c]!=0&&fits[c].ok){auto&x=fits[c];int at=14+12*k;double rho=rhoFor(which,day);for(int i=0;i<x.n;i++){int a=g.ta[x.ids[i]];double effect=delta[c]*x.normalized[i]*g.scale[a];double w=1;for(int b=at;b<BARS;b++){ret[b][a]+=effect*w;w*=rho;}}}
// Do NOT read future outcomes yet: save each causalprojection membership/R first.
// Remaining causalimpulses later in day may affect an earlier overlapping label.
// Store clockfits; all Y scores therefore evaluated only after entireday generated.
for(int c=0;c<C;c++)stored[k][c]=fits[c];
if(k==K-1){for(int kk=0;kk<K;kk++)for(int c=0;c<C;c++){auto&x=stored[kk][c];if(!x.ok)continue;for(int h=0;h<H;h++)if(g.complete[day][kk][c][h]){double Y[T],rhs[3]={},num=0;int entry=13+12*kk;for(int j=0;j<x.n;j++){int a=g.ta[x.ids[j]];double y=0;for(int b=entry+1;b<=entry+steps[h];b++)y+=ret[b][a];Y[j]=y/g.scale[a];num+=x.rd[j]*Y[j];for(int l=0;l<3;l++)rhs[l]+=x.X[j][l]*Y[j];}double by[3];for(int l=0;l<3;l++)by[l]=dot3(x.inv[l],rhs);int leaf=c*4+h;double main=num/(x.n*sqrt(x.r2/x.n));sum[leaf]+=main;count[leaf]++;
// Exact ShermanMorrison FWL leave-one-target-out identity, no newfitparameter.
for(int t=0;t<T;t++)if(g.tc[t]==c){double lscore=main;for(int j=0;j<x.n;j++)if(x.ids[j]==t){double denom=1-x.lev[j],ss=x.r2-x.rd[j]*x.rd[j]/denom;if(x.n-1<5||denom<=1e-10||ss/(x.n-1)<1e-20){lok[t][h]=false;lscore=0;}else{double ey=Y[j]-dot3(x.X[j],by);double nn=num-x.rd[j]*ey/denom;lscore=nn/((x.n-1)*sqrt(ss/(x.n-1)));}break;}ls[t][h]+=lscore;}
}}}}
for(int l=0;l<12;l++){out.valid[day][l]=count[l]>=4;out.daily[day][l]=count[l]?sum[l]/count[l]:0;}for(int t=0;t<T;t++)for(int h=0;h<H;h++){int l=g.tc[t]*4+h;out.loo[day][t][h]=lok[t][h]&&count[l]?ls[t][h]/count[l]:NAN;}}
}
Decisions infer(const Geo&g,const Output&o){Decisions d{};d.support=true;double blocks[15][12]={},obs[12],u[15][12]={},ss[12]={};int n[12]={};for(int l=0;l<12;l++){int thirds[3]={};for(int b=0;b<15;b++){double s=0;int cnt=0;for(int day=b*14;day<(b+1)*14;day++)if(o.valid[day][l]){s+=o.daily[day][l];cnt++;thirds[day/70]++;}if(cnt>=7){blocks[b][l]=s/cnt;n[l]++;}else blocks[b][l]=NAN;}if(n[l]<12||*min_element(thirds,thirds+3)<42)d.support=false;double mean=0;for(int b=0;b<15;b++)if(isfinite(blocks[b][l]))mean+=blocks[b][l];mean/=max(1,n[l]);for(int b=0;b<15;b++)if(isfinite(blocks[b][l])){u[b][l]=blocks[b][l]-mean;ss[l]+=u[b][l]*u[b][l];}if(ss[l]<=1e-20)d.support=false;obs[l]=ss[l]>1e-20?mean/sqrt(ss[l]/(max(1,n[l]-1)*max(1,n[l]))):0;}
if(!d.support)return d;int exceed[12]={};for(int b=0;b<1023;b++){double maximum=0;for(int l=0;l<12;l++){double total=0;for(int k=0;k<15;k++)total+=g.signs[b][k]*u[k][l];double den=(n[l]*ss[l]-total*total)/(n[l]-1);double t=den>1e-20?abs(total)/sqrt(den):0;maximum=max(maximum,t);}for(int l=0;l<12;l++)if(maximum>=abs(obs[l]))exceed[l]++;}
for(int l=0;l<12;l++){d.reject[l]=(1+exceed[l])/1024.<=.025;if(!d.reject[l])continue;double dir=obs[l]>0?1:-1;bool stable=true;for(int half=0;half<2;half++){double s=0;int cnt=0;for(int day=half*105;day<(half+1)*105;day++)if(o.valid[day][l]){s+=o.daily[day][l];cnt++;}if(cnt==0||dir*s<=0)stable=false;}int c=l/4,h=l%4;for(int t=0;t<T;t++)if(g.tc[t]==c){double s=0;int cnt=0;for(int day=0;day<DAYS;day++)if(o.valid[day][l]){if(!isfinite(o.loo[day][t][h]))stable=false;else{s+=o.loo[day][t][h];cnt++;}}if(cnt==0||dir*s<=0)stable=false;}d.lead[l]=stable;}return d;}
int main(int argc,char**argv){try{if(argc!=7)throw runtime_error("args geometry case mode seed trials outfile");Geo g;loadgeo(g,argv[1]);int which=stoi(argv[2]),mode=stoi(argv[3]),trials=stoi(argv[5]);mt19937_64 rg(stoull(argv[4]));vector<double> base(DAYS*BARS*A);Output out;int nr[4][4]={};int per[7][9][12]={},any[7][9]={},all[7][9]={},supported[7][9]={};double grid[9]={0,.05,.1,.2,.3,.4,.5,.75,1};
for(int trial=0;trial<trials;trial++){basepaths(g,which,rg,base);if(mode==0){array<array<double,3>,4> ds={array<double,3>{0,0,0},array<double,3>{.5,0,0},array<double,3>{0,-.5,0},array<double,3>{.5,-.5,0}};for(int cf=0;cf<4;cf++){compute(g,base,which,ds[cf],out);auto z=infer(g,out);bool bad=false,badlead=false;for(int l=0;l<12;l++)if(ds[cf][l/4]==0){bad=bad||z.reject[l];badlead=badlead||z.lead[l];}nr[cf][0]+=bad;nr[cf][1]+=badlead;nr[cf][2]+=z.support;nr[cf][3]+=out.numerical;}}else{for(int alt=0;alt<7;alt++)for(int e=0;e<9;e++){array<double,3> ds={0,0,0};if(alt<6)ds[alt/2]=(alt%2?-1:1)*grid[e];else ds={grid[e],-grid[e],grid[e]};compute(g,base,which,ds,out);auto z=infer(g,out);bool ay=false,al=true;for(int l=0;l<12;l++)if((alt<6&&l/4==alt/2)||(alt==6)){per[alt][e][l]+=z.lead[l];ay=ay||z.lead[l];al=al&&z.lead[l];}any[alt][e]+=ay;all[alt][e]+=al;supported[alt][e]+=z.support;}}if((trial+1)%512==0)cerr<<"case="<<which<<" mode="<<mode<<" completed="<<trial+1<<"/"<<trials<<endl;}
ofstream f(argv[6]);f<<setprecision(17)<<"{\"case_id\":"<<which<<",\"mode\":"<<mode<<",\"trials\":"<<trials<<",\"seed\":\""<<argv[4]<<"\",\"null\":[";for(int cf=0;cf<4;cf++){if(cf)f<<",";f<<"["<<nr[cf][0]<<","<<nr[cf][1]<<","<<nr[cf][2]<<","<<nr[cf][3]<<"]";}f<<"],\"power\":[";for(int a=0;a<7;a++){if(a)f<<",";f<<"[";for(int e=0;e<9;e++){if(e)f<<",";f<<"{\"any\":"<<any[a][e]<<",\"all\":"<<all[a][e]<<",\"supported\":"<<supported[a][e]<<",\"per_leaf\":[";for(int l=0;l<12;l++){if(l)f<<",";f<<per[a][e][l];}f<<"]}";}f<<"]";}f<<"]}\n";return 0;}catch(const exception&e){cerr<<e.what()<<endl;return 2;}}
