from pathlib import Path
import hashlib,json,math,subprocess
P=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def put(name,x):(P/name).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
sup=json.loads((P/'EXACT_SUPPORT_RAW_RESULT_V1.json').read_text())
put('EXACT_SUPPORT_INTERPRETATION_V1.json',{'classification':'PASS_EXACT_TIMESTAMP_AND_TRAINING_COUNT_SUPPORT_NOT_NUMERICAL_OR_INFORMATION_CERTIFICATION','raw_sha256':sha(P/'EXACT_SUPPORT_RAW_RESULT_V1.json'),'all12_timestamp_leaves_pass':sup['all_exact_timestamp_support_gates_pass'],'no_future_selected_target_subset':True,'numerical_rank_and_feature_variance_remain_synthetic_and_future_failclosed_gates':True,'market_authority':False})
plan={'schema':'TRIAD_V2_EXACT_STOCHASTIC_CERTIFICATION_PLAN_V1','status':'FROZEN_BEFORE_EXECUTION_NO_METHOD_TOURNAMENT','preconditions':{'semantic_interpretation_sha256':sha(P/'SEMANTIC_INTERPRETATION_V1.json'),'timestamp_support_interpretation_sha256':sha(P/'EXACT_SUPPORT_INTERPRETATION_V1.json')},'bindings':{f.name:sha(f) for f in [P/'TRIAD_V2_ESTIMAND_NUISANCE_DESIGN_V1.json',P/'orthogonal_score_v2.py',P/'exact_geometry_worker_v1.cpp',P/'build_exact_geometry_v1.py',P/'EXACT_SYNTHETIC_GEOMETRY_V1.txt',P/'EXACT_SYNTHETIC_GEOMETRY_BINDINGS_V1.json',P/'stochastic_certification_driver_v1.py',P/'stochastic_invariants_v1.py']},'compiler':{'command':'g++ -O3 -std=c++17 -Wall -Wextra exact_geometry_worker_v1.cpp -o triad_v2_worker','version':subprocess.check_output(['g++','--version'],text=True).splitlines()[0],'binary_sha256':sha(Path('/tmp/triad_v2_worker')),'fast_math':False},
'geometry':{'relations':107,'cohorts':[{'name':'G10_MONETARY_TRIADS','relations':56,'distinct_targets':23},{'name':'MANAGED_EXTENSION_TRIADS','relations':32,'distinct_targets':11},{'name':'OTHER_EXTENSION_TRIADS','relations':19,'distinct_targets':10}],'horizons_minutes':[15,30,60,240],'two_sided_leaves':12,'prefix_days':90,'evaluation_days':210,'calendar_blocks_days':14,'calendar_blocks':15,'clock_hours_UTC':list(range(8,16)),'M5_path_bars_per_day':146,'bar_labels':'06:50 through18:55; q=t-10min, entry=t-5min; future increments entry+5 throughentry+h','masks':'Exact original75 archive causal relation and fullclock futureavailability; no synthetic outcome-selected membership, zeroimputation or clockcompression. Original gap pattern is present in EVERY stress case.'},
'nuisance_uncertainty':{'current_m':'Recompute random full causal D/X projection for eachclock, trial and alternative. Includes predictor-nuisance estimation uncertainty and feature-control covariance drift. Fixed prefixnormalizers conditioned as already accepted predictor-only observations, not oracle unknown modelparameters. V1 residualization betas unused.','forward_g':'Exactly elided only after pathwise proof: for ANY finite estimated daily10column beta, at fixedUTCclock g=Xb and RD^Tg=0, including eachleave-one-target-out refit. Arbitrary noisy, drifting g estimates produce IDENTICAL psi and rejection. Chronological actual learner/maturity/purge verified separately by12 semantic tests and exactactual trainingcount ledger. No fixed oracle residual assumption; bootstrap gfit uncertainty has exactlyzero sensitivity.','rank_adapter':'3column Gram inverse aftercolumnRMS scaling; determinant>1e-12, columnRMS>1e-12, RD_RMS>=1e-10; failsclosed. This numerical adapter is frozen and tested against reference SVD on fixedfixtures. Positive Gram rank3 defines same projection span. Numerical rank/variance failures reduce support, never count as null evidence.'},
'inference':{'method':'JOINT_CALENDAR_BLOCK_WILD_BOOTSTRAP_T_MAXT_V1','nominal_family_alpha':0.025,'FWER_ceiling':0.05,'bootstrap_draws':1023,'common_sign_bank_seed':2026100524,'law':'One identical Rademacher sign peroriginal14day calendarblock acrossall12 centered blockscore leaves; studentize observed and resampled scores, single-stepmaximumabsoluteT; p=(1+#maxT>=absT)/1024. Common signs preservecontemporaneouscrossleaf dependence. Resampling conditional onfull estimatedscore vector; random nuisancepredictorprojection generated ineachjointMonteCarlo trial.','complete_procedure':'Paid significance, bothfixed105dayhalf signs, everydeclared singletargetleaveout aggregatedscore sameorientation, rank3/df2 eachsubset, wholefamily support. Both paid significance-only and finallead false-null rejection count are reported and gated. No universalcohort direction.'},
'support':{'minimum_clocks_per_day':4,'minimum_days_per_block':7,'minimum_supported_blocks':12,'minimum_days_per70daythird':42,'complete12leaf_family_required':True,'montecarlo_full_family_support_lower_bound':0.95,'support_uncertainty_z':3.5,'all_numeric_failures_reported':True,'no_unsupported_trial_pruning':True},
'DGP':{'joint_quoted_assets':'75 canonicallyoriented assetlog-return paths with5 fixedcurrencycontrast factors and8 deterministicquote-book factors. Algebra exact as3signedleg sum, not synchronous exchange/parity/arbitrage. Alltargetreturns share same rho percohortclock undernull; beta maydrift withcalendarstate.','serial':'Withinobserved M5day ARrho withstationaryfirstbar; full146barpath generatesjointoverlappingfuturehorizons. Independent dailyinitial innovations; crossdayAR is NOT claimed bythisenvelope. Missingarchive clocks masked inoriginalcalendar.','innovations':'Baselineunit normal. t5unitvariance via normal*sqrt(3/chi2_5). Centeredchi2_3/sqrt6 skew. Shared draws across75assets.','fixed_factor_loadings':'Canonicalcurrency contrast sin(index*(j+1)*sqrt2) differences for j0..4; .25sin(assetindex*(j+1)*sqrt3) forquote-bookj0..7; builder reproducible. Sourceprefixown60RMS setsasset scale, medianrelatedrelations for44targets, mediantargetscale forother31. SourcepositiveprefixrelationRMS normalizes causalclosure feature BEFORE clipping[-3,3].','cases':[{'id':0,'name':'NORMAL_WEAK','rho':0.1},{'id':1,'name':'AR025','rho':0.25},{'id':2,'name':'AR050','rho':0.5},{'id':3,'name':'PERSISTENT_INTRADAY','rho':'0.5^(1/288);daily reset; not crossdayAR050'},{'id':4,'name':'HEAVY_T5','rho':0.1},{'id':5,'name':'CENTERED_SKEW_CHI3','rho':0.1},{'id':6,'name':'HETEROSCEDASTIC','rho':0.1,'daily_scale':'exp(.45Z-.2025)'},{'id':7,'name':'STRONG_COMMON_FACTOR','rho':0.1,'loading_change':'column0x4; allothercolumnsx.4 beforefixedvariance normalization; genuinelyalteredjointcorrelation'},{'id':8,'name':'FEATURE_COVARIANCE_DRIFT','rho':0.1,'loading_change':'bookfactors .25+1.5day/209;currencycolumn0x1.5'},{'id':9,'name':'BASELINE_REGIME_DRIFT','rho':'0.1 first105days, .5 next105'},{'id':10,'name':'COMBINED_COVARIANCE_BASELINE_VARIANCE_CHANGE','rho':'.25 first105days, .5next105','book_scale':'.35 then1.75','daily_variance_scale':'.6 then1.3'}],
'partial_nulls':[{'id':0,'name':'GLOBAL_NULL','delta':[0,0,0]},{'id':1,'name':'G10_ONLY','delta':[0.5,0,0],'true_null_cohorts':[1,2]},{'id':2,'name':'NEGATIVE_MANAGED_ONLY','delta':[0,-0.5,0],'true_null_cohorts':[0,2]},{'id':3,'name':'HETEROGENEOUS_TWO_CONTEXTS','delta':[0.5,-0.5,0],'true_null_cohorts':[2]}],
'alternative_law':'At eachdecision, add delta_c*(currentRD/currentRMS)*sourceownscale to eachactivetarget firstfutureM5innovation atq+10min, propagateAR response throughremainingday. Allclockfeatures formed BEFORE theirinjection; saveprojectionbeforefuturelabels; latercausalimpulses mayaffectearlieroverlapping4h labels. True-nullcohort receives noownimpulse; itsconditionalmean remains common AR ownlastchange span evenwhen relationalbridgescontainnonnullprices. Future response horizon covariance comes fromonecommon assetpath, notindependentlysimulatedhorizonleaves.',
'null_assumptions':'Fixed actualtimestamp masks conditionallymean-ignorable; common withincohort/clock linear ownbaseline. No claim of robustness to identity-specificbeta, arbitrary nonlinearbaseline, informativefuture missingness, arbitrary crossdaylongmemory. Finite syntheticenvelope, notgeneral theorem ofwildbootstrapstrongFWER.'},
'precision':{'required_null_cells':44,'uncertainty_rule':'MAX of Wilson upper(z3.5) and exact ClopperPearson upper(alpha=.05/88) per44global/partialnullcells. Support gate MIN of Wilsonlower(z3.5) and exact ClopperPearsonlower(alpha=.05/88). Bonferroni88 one-sided events (44FWERupper+44supportlower) simultaneouscoverage>=.95 under IID simulation trials. Finalleadfalse-event subset ofpaid-significancefalse-event; reportboth, no independenceassumption betweenconfigurations. No point-estimate-only pass.','desired_simultaneous_halfwidth_at_p05':0.01,'derivation':'ceil(z^2*.05*.95/.01^2)=5819;roundUP tomultiple1024=6144','null_trials_per_case':6144,'null_seed':'2026100522 +1009*case_id','power_trials_per_case':2048,'power_derivation':'ceil(1.96^2*.8*.2/.02^2)=1537;roundUP tomultiple1024=2048','power_seed':'2026100523 +1009*case_id','no_extension_reseed_or_gate_adjustment':True},
'power':{'cases':[0,2,7,10],'alternatives':['G10_POSITIVE','G10_NEGATIVE','MANAGED_POSITIVE','MANAGED_NEGATIVE','OTHER_POSITIVE','OTHER_NEGATIVE','HETEROGENEOUS_POS_NEG_POS'],'effect_grid':[0,0.05,0.1,0.2,0.3,0.4,0.5,0.75,1.0],'effect_units':'IncrementalfirstfutureM5own-leg innovation per1currentclock relationalRDrms, infixed sourceprefixown60RMS units; standardizedsyntheticcoefficient, NOT bps/profit or SDofdailyteststatistic.','confidence':'Wilson z1.96 at everygrid cell; perleaf, anypaidlead andallnonnullleaves reported.','minimum_reliably_detectable':'Smallestgrid effect forANY paid localcohortlead withWilsonlower>=.80, separatelyeachlocalizedsign/cohort/stress. Notbesthorizonfreepass becausecommon12leafmaxT applies.','pass':'Completecurvesand lower>=.80 at SOME fixedgrid effect<=1 forALLsixlocalized alternatives inALLfourpowercases; else LOW_POWER_INCONCLUSIVE stop. Heterogeneouscurve required characterization, no universal-signgate. Diagnostic allleafpower doesnotgate.','economic_sensitivity':'Unknown realcost/event/effect scale means noeconomic powerclaim; futureEUR200 certification remainsseparate.'},
'execution_order':'Frozenplan/code/geometry commit first; deterministic invariants; alltrials ofcase0 global+partialnulls;rawcase checkpoint BEFORE interpretation. Ifanynull/support/numericimplementationgate failsSTOP, do notrunlatercasesorpower. Otherwisecase1...10. AfterallnullPASS runcompletefrozenpowercases similarlycheckpoint. No partialtrialcount inference orresult-basedcase selection.','raw_result_columns':['any_true_null_paid_significance','any_true_null_complete_lead','fullfamily_supported_trials','numerical_clock_failures'],'stability_breadth_included':True,'closure':'Failure closesonlythisexactV2 estimand/inference law atpreoutcome scope; broaderrelationalfamilyOPEN; V1untouched; no V3 inthistask.','authority':{'real_response_openings':0,'future_real_signed_response_computations':0,'broker_contacts':0,'historical_requests':0,'new_data':0,'confirmation':False,'candidate_promotion':False}}
put('EXACT_STOCHASTIC_CERTIFICATION_PLAN_V1.json',plan)
print('plan_sha256',sha(P/'EXACT_STOCHASTIC_CERTIFICATION_PLAN_V1.json'))
