"""Count durable identity/provenance metadata; never recompute price responses."""
import json,gzip,hashlib,pathlib,collections
P=pathlib.Path('.');S=P/'research_core_v3/state';O=P/'research_core_v4/audit_v2'
def read(f):return json.loads(pathlib.Path(f).read_text())
def sha(f):return hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()
manifest=read(S/'PRIMARY_145_INPUT_MANIFEST_V1.json');core=read(S/'INCLUSIVE_FULL_DEPTH_DISCOVERY_CORE_V1.json');q=json.load(gzip.open(S/'ACCEPTED_DATA_QUALITY_TABLE_V1.json.gz','rt'));front={r['symbol_id'] for r in q['rows']};primary={r['symbol_id'] for r in manifest['primary_series']};assert len(front)==1576 and len(primary)==145 and primary<=front
broad=read(S/'BROAD_145_DEVELOPMENT_SURFACE_MANIFEST_V1.json');corrected=read(S/'CORRECTED_145_DEVELOPMENT_MANIFEST_V2.json');assert {r['symbol_id'] for r in broad['records']}==primary=={r['symbol_id'] for r in corrected['records']};assert broad['cell_count']==corrected['cell_count']==7975
# Verify entire compressed objects by bytes against manifests; never open leaf tables.
shards=[]
for man in [broad,corrected]:
 for r in man['shards']:
  f=S/r['path'];assert sha(f)==r['sha256'];shards.append({'ref':str(f),'sha256':r['sha256']})
fric=set();led=[]
for plan,result in [('MAXT14_AUTHENTIC_FRICTION_ACQUISITION_PLAN_V2','V7_GLOBAL_FRICTION_TRIAGE_RESULT_AUDIT_V1'),('WAVE2_AUTHENTIC_FRICTION_ACQUISITION_PLAN_V1','V8_WAVE2_FRICTION_RESULT_AUDIT_V1'),('WINNER_FIRST_FRICTION_ACQUISITION_PLAN_V1','V9R1_WINNER_FIRST_RESULT_AUDIT_V1')]:
 d=read(S/(plan+'.json'));a=read(S/(result+'.json'));ids={r['symbol_id'] for r in d['targets']};fric|=ids;led.append({'plan_ref':str(S/(plan+'.json')),'result_ref':str(S/(result+'.json')),'unique_target_ids':sorted(ids),'count':len(ids),'completion_capture':a['capture'],'status':a['status']})
assert fric<=primary
us=read(S/'US24_CROSS_SECTIONAL_RETURN_ACTIVITY_STATE_WAVE_DESIGN_V1.json');usids={r['symbol_id'] for r in us['universe']['symbols']};extended=primary|usids
miss=read(S/'PROJECT_WIDE_HIERARCHICAL_MISSED_EDGE_AUDIT_V1.json');cc=collections.Counter(c for r in miss['records'] for c in r['classes']);assert dict(cc)==miss['classification_counts'];assert all(pathlib.Path(f).exists() for r in miss['records'] for f in r['refs'])
recent=read(P/'research_core_v4/state/VARIANCE_COMPOSITION_DESIGN_V1.json');exact18=set(sum(recent['memberships'].values(),[]));disp=read(P/'research_core_v4/state/RESIDUALIZED_DISPERSION_DESIGN_V1.json');exact12=set(sum(disp['memberships'].values(),[]));assert exact12<=exact18<=primary
report={'schema':'mxm.v4.universe-utilization-accounting.v1','starting_head':'17ea88a78e2c61b22844e3332bfed6facbd6d23f','status':'COMPLETE_DEFINED_SCOPE_ACCOUNTING_WITH_EXPLICIT_GLOBAL_IDENTIFIABILITY_LIMITS','counting_law':'Unique symbol IDs within explicitly evidenced stage/scope. Parameters, repeated mechanisms, price-only indicators, planning targets and independent dates are not additional identities. Neither usable economic test nor confirmation is inferred from acquisition.',
'frontier':{'authoritative_eligible':len(front),'current_metadata_inventory':5324,'current_accessible_EPOCH22':1689,'buy_feasible_EPOCH22':1647,'both_feasible_EPOCH22':1607,'historical_accessible':1690,'historical_non_test_feasible':1641,'historical_both_feasible':1609,'epoched_source':'evidence/BROKER_NATIVE_COMPETITION_UNIVERSE_CAPTURE_EPOCH22_ACCEPTANCE_V1.json','historical1641_source':'research_core_v3/state/LEGACY_INPUT_INSPECTION_V1.json; historical accepted structural derivative rows, not current buy feasibility','no_current_broker_verification':True},
'accepted_primary':{'M5_ids':145,'M5_rows':sum(r['row_count'] for r in manifest['primary_series']),'percent_frontier':100*145/1576,'outside_primary':1431,'asset_class_counts':dict(collections.Counter(r['asset_class'] for r in core['primary_core'])),'primary_ids':sorted(primary),'supplementary_accepted_not_primary_ids':[r['symbol_id'] for r in manifest['supplementary_original_series']],'accepted_primary_not_untouched':True,'raw_archive_recovered_this_task':False,'source_archives':[manifest['original_capture_sha256'],manifest['delta_capture_sha256']]},
'real_response_exposure':{'primary145_mechanism_discovery_and_real_development':145,'primary_broad_cells':7975,'mechanism_families':6,'primary_corrected_all_cells':7975,'manifest_ids_and_all_shard_byte_hashes_verified':True,'primary_plus_explicit_US31_real_response_scope_unique_ids':len(extended),'extra_US_ids':sorted(usids-primary),'broader156_scope_declared_result':'CAUSAL_REGIME_CONTEXT_ROUTED_RESPONSE_DEVELOPMENT_RESULT_V1.json and its preoutcome audit document156 tested; exact member ledger not independently bound in these aggregate summaries','usable_support_not_equivalent_to_exposure':True,'global_all_V2_V3_V4_usable_response_unique_count':None,'global_count_reason':'Heterogeneous result documents lack one exhaustive stage-qualified identity ledger. Known156 declared broad response cohort and independently identified155 union are reported separately, never asserted as complete1576 exposure.'},
'recent_scopes':{'exact18':18,'exact12':12,'exact18_ids':sorted(exact18),'exact12_ids':sorted(exact12),'accepted_primary_outside_exact18':127,'accepted_primary_outside_exact12':133,'percent_frontier_exact18':100*18/1576,'percent_primary_exact18':100*18/145,'first_real_V4_and_variance_union_response_ids':18,'online_and_dispersion_no_real_response':True,'bottleneck':'Same eighteen price identities, one response horizon, common support and universal lead decision reused despite broad accepted diversity; no generic information exhaustion established.'},
'authentic_friction':{'completed_primary_triage_unique_ids':len(fric),'completed_primary_triage_ids':sorted(fric),'completed_campaigns':led,'interpretation':'Authentic sampled event-time bid/ask friction evaluation, not every event, slippage or economic certification.84-symbol planned gross-survivor scope is not certified profitability. Existing summaries retain unresolved formal decisions.','global_all_history_unique_authenticated_friction_count':None},
'economic_testing':{'primary_broad_economic_certification':0,'candidate_certified':0,'V4_economic_certification':0,'declared156_router_economic_support_screening':156,'economic_support_screening_is_not_authentic_all_in_EUR200_test':True,'global_unique_full_economic_tests':None,'reason':'No exhaustive symbol-stage registry connects all historical V2 experiments and later partial-cost screens; cannot manufacture exact unique count from28 economic outcome events or7975 cells.'},
'confirmation':{'V4_opened':False,'protected_forward_opened':False,'V3_stageA_US24_disjoint_confirmation_cohort':31,'V3_confirmation_ref':'research_core_v3/state/US24_LOW_ACTIVITY_REVERSAL_STAGE_A_ENTRY_REPLICATION_RESULT_V1.json','V3_stageA_freeze_ref':'research_core_v3/state/US24_LOW_ACTIVITY_REVERSAL_TWO_STAGE_EXIT_DESIGN_V1.json','V3_temporal_tests_not_all_genuinely_disjoint':True,'global_distinct_V2_V3_confirmation_union':None},
'historical_regions':{'recounted_records':len(miss['records']),'nonexclusive_counts':dict(cc),'all_refs_exist':True,'record_scopes':[{'id':r['id'],'scope':r['scope'],'classes':r['classes'],'historical_state':r['state'],'refs':r['refs']} for r in miss['records']],'stale_status_warning':'Historical missed-edge audit predates later ORB/CRM/ADBE/PEP/SHB closures; current coverageV2 and V4 refreshes prevail. Counts describe historical regions, not current open leads or individual symbols.','friction_examples':'H24/H48 thirteen multiplicity symbols: twelve authentic fresh spread intersections dominated gross, EURDKK commission lower-bound dominated gross. H6 fourteen and XPT exact friction closures remain exact. Path six exact exit-rescue family later closed; no restoration.'},
'prospective_broad_use':'Recover accepted archive hashes without broker contact, freeze economic/structural-context cohorts from quality/schedule/identity metadata; causal source family and horizons jointly controlled. Reuse is exposed development, never confirmation. No free symbol/context selection; do not blindly reapply closed law to more symbols.',
'future_frontier_expansion':'Coherent outcome-blind mechanism/context waves selected by novelty, support/dependence and authenticated execution prospects; adaptive size, transport chunks irrelevant to scientific scope; route ready and governance authorization before any broker call.',
'new_market_responses':0,'broker_contacts':0,'historical_requests':0,'orders':0,'source_binding':{},'compressed_surface_files_verified':shards}
refs=['PRIMARY_145_INPUT_MANIFEST_V1.json','INCLUSIVE_FULL_DEPTH_DISCOVERY_CORE_V1.json','ACCEPTED_DATA_QUALITY_TABLE_V1.json.gz','BROAD_145_DEVELOPMENT_SURFACE_MANIFEST_V1.json','CORRECTED_145_DEVELOPMENT_MANIFEST_V2.json','PROJECT_WIDE_HIERARCHICAL_MISSED_EDGE_AUDIT_V1.json','PROJECT_WIDE_RESEARCH_DESIGN_COVERAGE_AUDIT_V2.json']
report['source_binding']={str(S/f):sha(S/f) for f in refs}
(O/'UNIVERSE_UTILIZATION_AUDIT_V1.json').write_text(json.dumps(report,sort_keys=True,indent=2)+'\n');print({'friction':len(fric),'extended':len(extended),'primary':145,'rows':report['accepted_primary']['M5_rows'],'counts':dict(cc)})
