"""Freeze one exact law before actual mask/support inspection or simulation."""
import json,pathlib,hashlib,datetime,math
R=pathlib.Path('.');B=R/'research_core_v4/triad_v1'
def h(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
inv=json.loads((B/'CANONICAL_FX_RELATION_COHORT_INVENTORY_V1.json').read_bytes());cohorts=['G10_MONETARY_TRIADS','MANAGED_EXTENSION_TRIADS','OTHER_EXTENSION_TRIADS'];assert set(inv['cohort_sizes'])==set(cohorts)
targets={c:sorted({x['target_symbol_id'] for x in inv['complete_relations'] if x['cohort']==c}) for c in cohorts}
p={'schema':'mxm.v4.triad.exact-mechanism-design.v1','mechanism':'CAUSAL_CURRENCY_TRIAD_RELATIONAL_STATE_INCREMENTAL_OWN_LEG_INFORMATION','status':'FROZEN_PREOUTCOME_LAW_NO_RESPONSE_AUTHORITY','inventory_ref':str(B/'CANONICAL_FX_RELATION_COHORT_INVENTORY_V1.json'),'inventory_sha256':h(str(B/'CANONICAL_FX_RELATION_COHORT_INVENTORY_V1.json')),'recovery_ledger_ref':str(B/'ACCEPTED_FX_ARCHIVE_RECOVERY_LEDGER_V1.json'),'recovery_ledger_sha256':h(str(B/'ACCEPTED_FX_ARCHIVE_RECOVERY_LEDGER_V1.json')),'protocol_ref':'research_core_v4/state/V4_DISCOVERY_PROTOCOL_V2.json','protocol_sha256':h('research_core_v4/state/V4_DISCOVERY_PROTOCOL_V2.json'),'no_free_selection':True,
 'cohorts':cohorts,'cohort_relation_counts':inv['cohort_sizes'],'cohort_target_ids':targets,'horizons_M5':[3,6,12,48],'horizons_minutes':[15,30,60,240],'leaves':[c+'|H'+str(n) for c in cohorts for n in [3,6,12,48]],'leaf_count':12,'individual_triad_hypotheses':False,'primary_features':1,'directions':'Two-sided sharedmaxT; every adjusted surviving leaf retained, no universal crosscohort direction.',
 'window':{'prefix_start_utc':'2025-09-16T00:00:00Z','prefix_calendar_days':90,'prefix_end_exclusive_utc':'2025-12-15T00:00:00Z','development_start_utc':'2025-12-15T00:00:00Z','development_calendar_days':210,'development_end_exclusive_utc':'2026-07-13T00:00:00Z','prefix_embargo':'Prefix uses past-only feature/control regression, no forward training label. Last prefix state never enters development response; development starts separately at08UTC.', 'remaining_accepted_interval':'Exposed development already; never declared disjointconfirmation.'},
 'causal_clock':{'decision_UTC_hours':[8,9,10,11,12,13,14,15],'weekdays_only':True,'bar_timestamp_interpretation':'UTC M5 bar-open label; conservatively available only after complete bar plusone additional5minute latency buffer. At decisiont use labelt-10min as last observableclose.', 'feature_history_offsets_from_last_bar_minutes':[0,5,60],'future_endpoint_bar_offsets_from_last_bar_minutes':[15,30,60,240],'endpoint_semantics':'Future response endpoints start from decisiont executable-information clock: entryreference labelt-5min (bar endingt), endpoint labelt+h-5min. Entryreference is not read before response authorization; clocks/masks only in support.', 'path_availability':'All actualM5 timestamp labels from entryreference through eachendpointh required, preserve3/6/12/48andintermediate5minute samples. No subM5 path; no priceforwardfill.','synchrony':'Exact matching bar labels are a sample-alignment convention, not simultaneous executable quotes or asynchronous-close freshness proof.'},
 'feature':{'law':'At causal lastobservablebarq, let C(q)=log P_uv(q)-log P_uA(q)+log P_vA(q), with inventoryfixed targetu<v and anchora. Raw relationalstate F(q)=C(q)-C(q-60min). This is an observed cycle-change discrepancy, not locked arbitrage.', 'controls':['intercept','canonical ownleg logchange qminusq-5min','canonical ownleg logchange qminusq-60min','seven UTCclock dummies for8..15'], 'prefix_fit':'Perrelation OLSprojection F on controls using only complete causal prefixdecisionrows, no future labels. Pseudoinverse rcond1e-12 fixed. Prefixcenter/residual RMS fixed. No development refit.', 'normalized_state':'Residual / prefixRMS, clippedto[-3,3] prospectively. Fixed feature orientation inventorytarget-minusbridge. Both continuation and reversal paid in two-sidedfamily.', 'ownleg_outcome_later':'Canonical target logprice change between entryreference and eachendpoint, divided by frozen prefix ownleg60min logchange RMS. No response or priceendpoint computed in this task.', 'distinctness':'Three-instrument currency-algebra closure-change innovation, fixed monetary-anchor target and broad structural cohorts. No event-time quote revision, pairdelaysearch, factor-eigenmodel, cross-sectionaldispersionranking or rescue of prior exact scopes.', 'prefix_validity_gates':{'minimum_complete_prefix_clocks_per_relation':240,'prefix_design_rank':10,'minimum_residual_RMS':1e-10,'minimum_ownleg60min_RMS':1e-10,'all_relations_required':True,'no_postsupport_pruning':True}},
 'aggregation':{'law':'Equalweight available relations within each fixedtarget; equalweight targets within cohortclock; equalweight complete clocks withinday. A repeated target may not obtain extra weight from extra bridges.', 'clock_breadth':'At leastceil(0.5*declaredrelations) andceil(0.5*declaredtargets),minimum3targets; no data-drivenweight optimization.', 'daily_breadth':'At least4of8fixedclocks satisfy complete causal three-leg feature and ownleg fullpathavailability for thathorizon. Causal availability check uses onlytimestamps.', 'max_target_weight':'At most1/3 pereligibleclock; no isolatedtriadwinner.', 'response_concentration_later':'At least50percent of fixed declaredtargetweight has signconsistent targetmean; also removalofeachsingletarget leaves selectedcohort orientationunchanged. These selection gates require future exactsynthetic validation; never applied to realprices now.'},
 'support':{'calendar_days':210,'block_days':14,'potential_blocks':15,'minimum_valid_days_per_block':7,'minimum_supported_blocks_per_leaf':12,'minimum_observed_days_per_fixed70day_third':42,'complete_family_required':True,'support_failure':'DATA_LIMITED_SUPPORT_UNTESTED_NOT_NULL; stop exactdesign, no cohort/horizon removal or rescue. Missingness neverzero and calendarnevercompressed.'},
 'stability':{'law':'Two fixed105day halves: each must have supported mean in the globallyselected orientation. This reflects persistence across two longer currency-state windows; unrelatedcohorts remainindependentleads.', 'not_universal_default':True,'no_best_half_or_regime':True,'complete_procedure_calibration_required':True},
 'inference':{'method':'JOINT_CALENDAR_BLOCK_WILD_BOOTSTRAP_T_MAXT_V1','generic_plan_sha256':'a334f95e5d8c3e11317a1cad72e03d0953ab2c19e97d146d95592a5d2921be52','generic_implementation_sha256':'e948a3e36e546168f185d52c8a31a5caf0da7fe0f0c160eb3da3a492c56979d0','bootstrap_draws':1023,'nominal_family_alpha':.025,'FWER_ceiling':.05,'studentization':'Exactgeneric centered blockbootstrap-t with one common calendarmultiplier across12leaves; no independentrelationbootstrap. Exact score extraction covariance/prefix/masks require certification beforeanyresponse.', 'no_HAC_fallback':True,'no_tournament':True,'no_postresult_adjustment':True},
 'preoutcome_order':['Frozen design and timestamp-only support implementation','Actualtimestamp mask/support and prefixavailability checks','If anyfrozen gatefails persist blocker and stop; no fullcertificationorresponse','Only ifsupportpasses: freeze complete exactsyntheticDGP,implementation,trials,seeds,error/powergates before simulation','Rawsynthetic results beforeinterpretation','If everyexactgatepasses READY_NOT_EXECUTED forindependentgovernance'],
 'synthetic_requirement_not_yet_executable':{'status':'REQUIRES_COMPLETE_SUPPORT_FIRST_NOT_A_CERTIFICATION_PLAN','must_cover':['actual overlapping horizon endpoints','actual107relationtargetcurrencytopology','prefix estimation usingonlydisjointsynthetictraining','actualcausal mask/gaps','heavy tails','heteroscedasticity','serial AR025/AR050orstronger justifiedscoredependence','commonfactors','global andmultiplepartialnulls','localizedplusminus andheterogeneousdirections','completebreadthconcentrationstabilityselection'],'MC_precision':'Mustfreeze simultaneousuncertainty-derivedcount andseedswithimplementation beforeanysimulation; generic abstractresults cannotcertifythisdesign.'},
 'economics':{'claim':None,'unknown_friction_is_zero':False,'no_universal_bps_gate':True,'planning_only':'Alreadydurableauthenticminvolume,step,margin,conversion,spread/commissionandschedule mayguidefeasibilityonly. Current executablecost,slippage,marginEUR200andloggrowth remainunresolved.','information_before_exit':True},
 'closure_scope':'Only this exact frozen relation/cohortfeature/prefix/clock/horizon/support/inference/stability law mayblock. Broader CROSS_INSTRUMENT_RELATIONAL_STATE family remainsopen. No old classification reinterpretation.',
 'real_response_authorized':False,'maximum_response_openings':0,'broker_acquisition_authorized':False,'confirmation_authorized':False,'candidate_promotion_authorized':False}
(B/'EXACT_TRIAD_MECHANISM_DESIGN_V1.json').write_text(json.dumps(p,sort_keys=True,indent=2)+'\n');print(json.dumps({'targets':{c:len(v) for c,v in targets.items()},'design_sha256':h(str(B/'EXACT_TRIAD_MECHANISM_DESIGN_V1.json'))}))
